require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# Most of code in this project to not use Unit test
# But uses end-user tests, so only small margin
# of files are unit and should describe classes
RSpec/DescribeClass:
  Include:
    - 'spec/common/classes/**/*'

# In those 3 folder we store E2E tests
# So they have a complicated structure
# All unit test are stored in spec/ooxml_parser
# So there should be no problems with that folder
RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/document/**/*'
    - 'spec/workbook/**/*'
    - 'spec/presentation/**/*'
