name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
        allow-failures: [false]
        check-coverage: [true]
        include:
          - ruby: head
            allow-failures: true
            check-coverage: true
          - ruby: 'jruby-9.4'
            allow-failures: false
            check-coverage: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gem dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Test with Rake
        run: bundle exec parallel_rspec spec
      - if: ${{ matrix.check-coverage }}
        name: Check `simplecov` line coverage
        run: cat coverage/.last_run.json | jq '.result.line' | grep -q '100'
